version: 2

packer: &packer
  docker:
    - image: tendermintdev/docker-hashicorp-go:latest
  working_directory: ~/packer

build-docker: &build-docker
  run:
    name: "Build docker image"
    command: |
      cd ${CIRCLE_BRANCH}
      docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      docker build -t tendermintdev/${CIRCLE_BRANCH} .
      docker push tendermintdev/${CIRCLE_BRANCH}

build-ami-validate: &build-ami-validate
  run:
    name: "Validate packer template"
    command: |
      cd ${CIRCLE_BRANCH}
      packer validate *.json

build-ami: &build-ami
  run:
    name: "Build AMI"
    command: |
      cd ${CIRCLE_BRANCH}
      packer build *.json

run-sim: &run-sim
  run:
    name: "Run simulation"
    command: |
      cd ami-gaia-sim/src
      if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
        go run start_sim.go ${BLOCKS} ${PERIOD} ${GAIA_COMMIT_HASH} ${SIM_BOT_DEV_CHANNEL} ${SIM_BOT_DEV_TOKEN}
      else
        go run start_sim.go ${BLOCKS} ${PERIOD} ${GAIA_COMMIT_HASH} ${SLACK_CHANNEL_ID} ${SLACK_TOKEN}
      fi

jobs:
  build:
    <<: *packer
    steps:
      - checkout
      - run:
          name: "Build AMI"
          command: |
            cd ami-gaia-sim
            packer validate *.json
            packer build *.json
      - *run-sim

  docker-hashicorp-go:
    machine: true
    steps:
      - checkout
      - *build-docker

  iam-management:
    machine: true
    steps:
      - checkout
      - *build-docker

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - *build-docker

  terragrunt:
    machine: true
    steps:
      - checkout
      - *build-docker

  docs-deployment:
    machine: true
    steps:
      - checkout
      - *build-docker

workflows:
  version: 2
  build-image:
    jobs:
      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment-yarn

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - docker-hashicorp-go:
          filters:
            branches:
              only: docker-hashicorp-go
