version: 2.1
parameters:
  gaia-commit-hash:
    type: string
    default: "master"
  blocks:
    type: string
    default: "100"
  genesis:
    type: string
    default: "false"
  check-id:
    type: string
    default: "0"


executors:
  packer:
    docker:
      - image: tendermintdev/docker-hashicorp-go:latest
    environment:
      GAIA_COMMIT_HASH: << pipeline.parameters.gaia-commit-hash >>
      BLOCKS: << pipeline.parameters.blocks >>
      GENESISS: << pipeline.parameters.genesis >>
      CHECK_ID: << pipeline.parameters.check-id >>

commands:
  build-docker:
    steps:
      - run:
          name: "Build docker image"
          command: |
            cd ${CIRCLE_BRANCH}
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t tendermintdev/${CIRCLE_BRANCH} .
            docker push tendermintdev/${CIRCLE_BRANCH}

  get-execmgmt-dev:
    steps:
      - run:
          name: "Install execmgmt"
          command: |
            git clone https://github.com/cosmos/tools.git
            cd tools/cmd/runsim/execmgmt && git checkout ${RUNSIM_COMMIT_HASH}
            go install

  build-gaia-sim-image:
    steps:
      - run:
          name: "Build gaia sim AMI"
          command: |
            export MSGTS=`execmgmt -notify -b ${BLOCKS} -p ${PERIOD} -s ${SLACK_TOKEN} -c ${SLACK_CHANNEL_ID} -g ${GAIA_COMMIT_HASH}`
            cd ami-gaia-sim
            packer validate gaiad.json
            packer build gaiad.json

  run-sim:
    steps:
      - run:
          name: "Run simulation"
          command: |
            if [[ "${GENESIS}" == "true" ]]; then
              execmgmt -gen -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID} -s ${SLACK_TOKEN}
            else
              execmgmt -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID} -s ${SLACK_TOKEN}
            fi

jobs:
  build:
    executor: packer
    steps:
      - checkout
      - run:
          name: "Run simulation"
          command: |
            cd ami-gaia-sim
            go install github.com/cosmos/tools/cmd/runsim/execmgmt

            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
              export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
              export MSGTS=`execmgmt -notify -b ${BLOCKS} -p ${PERIOD} -s ${SLACK_TOKEN_DEV} -c ${SLACK_CHANNEL_ID_DEV} -g ${GAIA_COMMIT_HASH}`
            else
              export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
              export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
              export MSGTS=`execmgmt -notify -b ${BLOCKS} -p ${PERIOD} -s ${SLACK_TOKEN_PROD} -c ${SLACK_CHANNEL_ID_PROD} -g ${GAIA_COMMIT_HASH}`
            fi

            packer validate gaiad.json
            packer build gaiad.json

            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              if [[ "${GENESIS}" == "true" ]]; then
                execmgmt -gen -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID_DEV} -s ${SLACK_TOKEN_DEV}
              else
                execmgmt -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID_DEV} -s ${SLACK_TOKEN_DEV}
              fi
            else
              if [[ "${GENESIS}" == "true" ]]; then
                execmgmt -gen -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID_PROD} -s ${SLACK_TOKEN_PROD}
              else
                execmgmt -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID_PROD} -s ${SLACK_TOKEN_PROD}
              fi
            fi

  ami-gaia-sim:
    executor: packer
    steps:
      - checkout
      - get-execmgmt-dev
      - build-gaia-sim-image
      - run-sim

  docker-hashicorp-go:
    machine: true
    steps:
      - checkout
      - build-docker

  iam-management:
    machine: true
    steps:
      - checkout
      - build-docker

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - build-docker

  terragrunt:
    machine: true
    steps:
      - checkout
      - build-docker

  docs-deployment:
    machine: true
    steps:
      - checkout
      - build-docker

workflows:
  version: 2
  build-image:
    jobs:
      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - docker-hashicorp-go:
          filters:
            branches:
              only: docker-hashicorp-go

  run-gaia-sim:
    jobs:
      - ami-gaia-sim:
          context: gaia-sim-dev
          filters:
            branches:
              only: master
