version: 2.1
parameters:
  runsim-commit-hash:
    type: string
    default: "master"
  gaia-commit-hash:
    type: string
    default: "master"
  blocks:
    type: string
    default: "100"
  genesis:
    type: string
    default: "false"
  check-id:
    type: string
    default: "0"


executors:
  packer:
    docker:
      - image: tendermintdev/docker-hashicorp-go:latest
    environment:
      GAIA_COMMIT_HASH: << pipeline.parameters.gaia-commit-hash >>
      BLOCKS: << pipeline.parameters.blocks >>
      GENESISS: << pipeline.parameters.genesis >>
      CHECK_ID: << pipeline.parameters.check-id >>
      RUNSIM_COMMIT_HASH: << pipeline.parameters.runsim-commit-hash >>

commands:
  build-docker:
    steps:
      - run:
          name: "Build docker image"
          command: |
            cd ${CIRCLE_BRANCH}
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t tendermintdev/${CIRCLE_BRANCH} .
            docker push tendermintdev/${CIRCLE_BRANCH}

jobs:
  ami-gaia-sim:
    executor: packer
    steps:
      - checkout
      - run:
          name: "Build execmgmt tool"
          command: |
            git clone https://github.com/cosmos/tools.git
            cd tools/cmd/runsim/execmgmt && git checkout ${RUNSIM_COMMIT_HASH}
            go install
      - run:
          name: "Build image and run sim"
          command: |
            export MSGTS=`execmgmt -notify -b ${BLOCKS} -p ${PERIOD} -s ${SLACK_TOKEN} -c ${SLACK_CHANNEL_ID} -g ${GAIA_COMMIT_HASH}`

            cd ami-gaia-sim
            packer validate gaiad.json
            packer build gaiad.json

            if [[ "${GENESIS}" == "true" ]]; then
              execmgmt -gen -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID} -s ${SLACK_TOKEN}
            else
              execmgmt -b ${BLOCKS} -p ${PERIOD} -g ${GAIA_COMMIT_HASH} -c ${SLACK_CHANNEL_ID} -s ${SLACK_TOKEN}
            fi

  docker-hashicorp-go:
    machine: true
    steps:
      - checkout
      - build-docker

  iam-management:
    machine: true
    steps:
      - checkout
      - build-docker

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - build-docker

  terragrunt:
    machine: true
    steps:
      - checkout
      - build-docker

  docs-deployment:
    machine: true
    steps:
      - checkout
      - build-docker

workflows:
  version: 2
  build-image:
    jobs:
      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - docker-hashicorp-go:
          filters:
            branches:
              only: docker-hashicorp-go

  run-gaia-sim:
    jobs:
      - ami-gaia-sim:
          context: gaia-sim-dev
          filters:
            branches:
              only: master

      - ami-gaia-sim:
          context: gaia-sim-prod
          filters:
            branches:
              only: ami-gaia-sim
