version: 2

packer: &packer
  docker:
    - image: hashicorp/packer:1.3.5
  working_directory: ~/packer

build-docker: &build-docker
  run:
    name: "Build docker image"
    command: |
      cd ${CIRCLE_BRANCH}
      docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      docker build -t tendermintdev/${CIRCLE_BRANCH} .
      docker push tendermintdev/${CIRCLE_BRANCH}

build-ami-validate: &build-ami-validate
  run:
    name: "Validate packer template"
    command: |
      cd ${CIRCLE_BRANCH}
      packer validate *.json

build-ami: &build-ami
  run:
    name: "Build AMI"
    command: |
      cd ${CIRCLE_BRANCH}
      packer build *.json

run-sim: &run-sim
  run:
    name: "Run simulation"
    command: |
      cd gaia_sim
      go get github.com/aws/aws-sdk-go
      go run start_sim.go

jobs:
  gaia-sim-ami:
    <<: *packer
    steps:
      - checkout
      - *build-ami-validate
      - *build-ami

  gaiad-validator-ecs:
    machine: true
    steps:
      - checkout
      - *build-docker

  gaiacli-ecs:
    machine: true
    steps:
      - checkout
      - *build-docker

  iam-management:
    machine: true
    steps:
      - checkout
      - *build-docker

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - *build-docker

  voyager-node-browser:
    machine: true
    steps:
      - checkout
      - *build-docker

  voyager-node:
    machine: true
    steps:
      - checkout
      - *build-docker

  terragrunt:
    machine: true
    steps:
      - checkout
      - *build-docker

  docs-deployment:
    machine: true
    steps:
      - checkout
      - *build-docker

workflows:
  version: 2
  build-image:
    jobs:
      - gaiad-validator-ecs:
          filters:
            branches:
              only: docker-gaiad-validator-ecs

      - gaiacli-ecs:
          filters:
            branches:
              only: docker-gaiacli-ecs

      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment-yarn

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - voyager-node-browser:
          filters:
            branches:
              only: docker-voyager-node-browser

      - voyager-node:
          filters:
            branches:
              only: docker-voyager-node

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - gaia-sim-ami:
          filters:
            branches:
              only: update-gaia-sim
