name: Build & Push rbuilder
#  Build & Push rebuilds the rbuilder docker using a manual trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=majita/rbuilder
          VERSION=latest
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./rbuilder
          file: ./rbuilder/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
